# Usefull links
# =============
# https://hub.docker.com/_/php/
# https://docs.docker.com/compose/overview/
# https://docs.docker.com/compose/compose-file/
#
# Usefull commands
# ================
#
# Start containers
# $ docker-compose up -d
#
# View running containers
# $ docker-compose ps
#
# Connect into command line of running container
# $ docker-compose run <container_name> bash
# where <name> could be fpm_flute, web_flute, db_flute.
# Container `fpm_flute` is most interesting as it has PHP, application code and connection to databse.
# Tip: `Ctrl+p` + `Ctrl+q` + `Enter` (to exit container bash)
#
# View docker logs
# $ docker-compose logs
#
# Stop containers
# $ docker-compose down
#
# Remove images
# $ docker rmi limoncelloflute_fpm

web:
  image: nginx
  container_name: web_flute
  ports:
    - "8080:80"
  links:
    - fpm
  volumes:
    - .:/app
    - ./docker/nginx.site:/etc/nginx/conf.d/default.conf:ro

fpm:
  build: ./docker/fpm
  container_name: fpm_flute
  links:
    - db
  volumes:
    - .:/app
    - ./docker/.env.app:/app/.env:ro
  working_dir: /app

db:
  image: percona
  container_name: db_flute
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: flute
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: flute
